# Generated by Django 4.2.4 on 2023-09-07 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='product_photos/', verbose_name='Фото')),
                ('manufacturer', models.CharField(max_length=255, verbose_name='Производитель')),
                ('color', models.CharField(blank=True, max_length=50, verbose_name='Цвет')),
                ('material', models.CharField(blank=True, max_length=50, verbose_name='Материал')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Себестоимость')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('width', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True, verbose_name='Ширина')),
                ('length', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True, verbose_name='Длина')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Количество')),
            ],
        ),
    ]